/**
 * Collage Prefix Usage Examples
 *
 * The COLLAGE_PREFIX constant identifies auto-generated collage images.
 * This allows you to easily filter and identify collages for batch operations.
 */

import { COLLAGE_PREFIX, generateCollage, blobToFile } from '../utils/collageGenerator';

// ============================================================================
// Example 1: Using the prefix constant in your own functions
// ============================================================================

function isAutoGeneratedCollage(filename) {
    return filename.startsWith(COLLAGE_PREFIX);
}

// Test usage:
console.log(isAutoGeneratedCollage('AUTO_COLLAGE_collage_1712957400000.png')); // true
console.log(isAutoGeneratedCollage('family_photo.jpg')); // false

// ============================================================================
// Example 2: Filter collages from a list of filenames
// ============================================================================

function filterCollagesFromImages(filenames) {
    return filenames.filter(filename => isAutoGeneratedCollage(filename));
}

const allFiles = [
    'AUTO_COLLAGE_collage_1234567890.png',
    'user_photo_1.jpg',
    'AUTO_COLLAGE_collage_1234567891.png',
    'user_photo_2.jpg',
];

const justCollages = filterCollagesFromImages(allFiles);
console.log(justCollages);
// Output: ['AUTO_COLLAGE_collage_1234567890.png', 'AUTO_COLLAGE_collage_1234567891.png']

// ============================================================================
// Example 3: Function to regenerate collages from Firebase Storage
// ============================================================================

async function regenerateCollagesFromStorage() {
    // Pseudocode - adapt to your Firebase setup
    const storage = getFirebaseStorage();
    const bucket = ref(storage, 'userPosts/');

    // List all files in storage
    const files = await listAll(bucket);

    // Filter to only auto-generated collages
    const existingCollages = files.items.filter(item =>
        item.name.startsWith(COLLAGE_PREFIX)
    );

    console.log(`Found ${existingCollages.length} existing collages`);

    // Now you can:
    // - Delete old collages and regenerate
    // - Update collages for existing posts
    // - Migrate to new collage format

    return existingCollages;
}

// ============================================================================
// Example 4: Firestore query to find posts with collages
// ============================================================================

async function findPostsWithCollages(db) {
    // Query for posts where first photo has the collage prefix
    // (Adapted based on your Firestore structure)

    const postsWithCollages = [];

    // This example assumes postPhotos is an array where [0] is the collage
    const querySnapshot = await getDocs(collection(db, 'userPosts'));

    querySnapshot.forEach((doc) => {
        const post = doc.data();
        if (post.postPhotos && post.postPhotos.length > 0) {
            // Check if first photo URL indicates a collage
            // (You'd need to check the filename from the URL)
            if (post.postPhotos[0].includes(COLLAGE_PREFIX)) {
                postsWithCollages.push({
                    postId: doc.id,
                    post: post,
                    collageUrl: post.postPhotos[0]
                });
            }
        }
    });

    return postsWithCollages;
}

// ============================================================================
// Example 5: Delete all auto-generated collages
// ============================================================================

async function deleteAllCollages(storage, dateFolder, userId) {
    // This would safely delete all collages generated by your system
    // without touching user-uploaded photos

    const path = `userPosts/${dateFolder}/${userId}/`;

    // In Firebase Storage, you'd typically:
    // 1. List all files in the path
    // 2. Filter for those starting with COLLAGE_PREFIX
    // 3. Delete each one

    console.log(`Would delete all files starting with "${COLLAGE_PREFIX}" from ${path}`);
}

// ============================================================================
// Example 6: Collage statistics
// ============================================================================

function getCollageStats(filenames) {
    const stats = {
        totalFiles: filenames.length,
        collageFiles: 0,
        userFiles: 0,
        collagePercentage: 0,
    };

    filenames.forEach(filename => {
        if (isAutoGeneratedCollage(filename)) {
            stats.collageFiles++;
        } else {
            stats.userFiles++;
        }
    });

    stats.collagePercentage = (stats.collageFiles / stats.totalFiles * 100).toFixed(2);

    return stats;
}

const stats = getCollageStats(allFiles);
console.log(stats);
// Output: {
//   totalFiles: 4,
//   collageFiles: 2,
//   userFiles: 2,
//   collagePercentage: '50.00'
// }

// ============================================================================
// Example 7: Validation function for Firebase Security Rules
// ============================================================================

// This could be used in Firebase security rules or validation logic:
//
// // In your Firestore/Storage rules, you might want to:
// // - Allow system to write files with COLLAGE_PREFIX
// // - Prevent users from creating files with this prefix
// // - Audit all collage creations
//
// Example JavaScript validation:

function isValidCollageUpload(filename, uploadedBySystem = false) {
    const hasPrefix = filename.startsWith(COLLAGE_PREFIX);

    // Allow only if uploaded by system (not user)
    if (hasPrefix && !uploadedBySystem) {
        return false; // User shouldn't create collage-prefixed files
    }

    // Allow user files (without prefix)
    if (!hasPrefix) {
        return true;
    }

    return uploadedBySystem;
}

console.log(isValidCollageUpload('AUTO_COLLAGE_photo.png', true));  // true (system upload)
console.log(isValidCollageUpload('AUTO_COLLAGE_photo.png', false)); // false (user attempt)
console.log(isValidCollageUpload('user_photo.jpg', false));         // true (normal user upload)

// ============================================================================
// Example 8: Batch operation - regenerate collages for old posts
// ============================================================================

async function regenerateOldCollages(postIds, onProgress) {
    // Use case: You want to regenerate collages with new format/quality

    let processed = 0;

    for (const postId of postIds) {
        try {
            // 1. Fetch the post
            // const post = await fetchPost(postId);

            // 2. Find the old collage
            // const oldCollageUrl = post.postPhotos[0];
            // if (!oldCollageUrl.includes(COLLAGE_PREFIX)) continue;

            // 3. Delete old collage
            // await deleteFile(oldCollageUrl);

            // 4. Regenerate new collage
            // const newCollage = await generateCollage(originalImages);

            // 5. Upload new collage
            // const newUrl = await uploadFile(newCollage);

            // 6. Update post
            // await updatePost(postId, { postPhotos: [newUrl, ...rest] });

            processed++;
            onProgress?.(processed, postIds.length);
        } catch (error) {
            console.error(`Failed to regenerate collage for post ${postId}:`, error);
        }
    }

    console.log(`Regenerated ${processed}/${postIds.length} collages`);
}

// ============================================================================
// Export all helper functions
// ============================================================================

export {
    isAutoGeneratedCollage,
    filterCollagesFromImages,
    regenerateCollagesFromStorage,
    findPostsWithCollages,
    deleteAllCollages,
    getCollageStats,
    isValidCollageUpload,
    regenerateOldCollages,
    COLLAGE_PREFIX,
};

