name: Delete Branch

on:
  push:
    branches:
      - master

jobs:
  delete-branch:
    runs-on: ubuntu-latest
    container:
      image: node:16
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Delete merged branch
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
        run: |
          # Get the branch name from the event payload
          branch="${GITHUB_REF#refs/heads/}"
          # Delete the branch
          git push origin --delete $branch
