name: Delete Branch

on:
  push:
    branches:
      - master

jobs:
  delete-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Delete merged branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Get the branch name from the event payload
          branch=${{ github.ref }}
          branch=${{ branch/refs\/heads\// }}
          # Delete the branch
          git push origin --delete $branch
